- hosts: builder
  sudo: yes
  connection: ssh

  pre_tasks:
    - lineinfile: line='127.0.0.1 docker-registry.example.com' dest=/etc/hosts

  roles:
    - role: docker_environment
      docker_opts: '--storage-driver=aufs'
    - role: known_hosts_github
    - role: ansible
    - role: docker_registry
    - role: java
    - role: jenkins
      tags: ['jenkins']
# this role is for those of us that need to use private repos
# uncomment and use ansible vault to add your deploy key into
# jenkins_deploy_keys/defaults/main.yml. remember to add your
# deploy key into github / bitbucket / etc
#    - role: jenkins_deploy_keys
#      tags: ['jenkins']
    - role: jenkins_jobs
      tags: ['jenkins_jobs']
